# Generated by Django 3.0.5 on 2020-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coralblogindexpage_coralblogpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='coralseopage',
            name='struct_org_type',
        ),
    ]
