# Generated by Django 3.0.5 on 2020-04-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200425_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coralpage',
            name='custom_template',
        ),
    ]
